### ISSUE TITLE
Feature Request: Wiki links

### ISSUE THREAD

**Issue by lukaskawerau** [lukakerr/Pine#20]
Would it be possible to allow links between `.md` files in the form of Wikilinks, i.e. `[[Other Note.md|Description]]`?  
That would make twig a perfect Markdown-Wiki app, which I've been looking for for ages.  
I've never worked with Swift before, otherwise I'd offer to help implement it.
It's kinda possible to do this with Atom, and [here's how the logic works in JS](https://github.com/lukaskawerau/mume/commit/aa7268cd779871a530aa7eb0ef50a232e50dcf8f), but Twig looks much nicer.  

Any chance this feature would be possible?

**Comment by lukakerr** [comment]
Currently the [markdown parser being used](https://github.com/lukakerr/cmark-gfm-swift) doesn't support wiki links at all, and I don't plan on adding support since it's not part of the [GitHub Flavored Markdown](https://github.github.com/gfm/) specification.

Although, Twig does support linking markdown files using the default syntax `[Note](./path/to/note.md)` and will open that note when the link is clicked on in the preview. Currently this is just in `master` and hasn't been released yet, but will be very shortly.

**Comment by lukakerr** [comment]
@lukaskawerau I’ve actually changed my mind on this. Since I’ve implemented markdown ‘extensions’ such as GitHub emojis, I plan on adding wiki links too.

Could you please just confirm the exact syntax? In your example above you’ve got [[Note.md|Description]] but I’ve seen in other places people use it as [[Description|Note.md]]

**Comment by lukaskawerau** [comment]
@lukakerr That's great news!  
The other syntax is correct, it's [[Description|Note.md]] :)

**Comment by lukakerr** [comment]
This has been implemented in 90527f4 and will be included in the next release.

<img width="953" alt="Screen Shot 2019-03-11 at 9 04 09 pm" src="https://user-images.githubusercontent.com/20056300/54115924-b9116a00-4441-11e9-8d0a-3c7d28a5f0ef.png">

As for autocomplete, I plan to implement autocomplete for all markdown syntax and files in the future, so haven't included that with this new feature.

In the next release if there are any issues with the WikiLink's feel free to reopen this issue or create a new one.
