### ISSUE TITLE
Unable to open the document with `open -a Pine xxxxx.md` in the terminal

### ISSUE THREAD

**Issue by maboloshi** [lukakerr/Pine#45]
In the terminal:
```sh
open -a Pine xxxxx.md
```
The pine app can be run, but pine app does not open xxxx.md

**Comment by lukakerr** [comment]
Thanks for reporting, this should be fixed in 5eb67ac

**Comment by maboloshi** [comment]
Update Pine to 0.0.8, the problem remained.

**Comment by lukakerr** [comment]
I will take another look.

**Comment by lukakerr** [comment]
Ok I believe this has been fixed in 9e75f52. One thing to note though, I don't think you can actually open files using `open -a Pine xxxx.md`, you need to specify the actual path of the application like so `open -a /Applications/Pine.app xxxx.md`. More information is [here](https://stackoverflow.com/a/27356325/6523193).
